### ISSUE TITLE
Add this badges !

### ISSUE THREAD

**Issue by devcss122** [devcss122/CP-Solutions#8]
Add this badges in Readme.

![](https://img.shields.io/badge/Prepare%20-ICPC-%23db164b)
link badge 1 - https://img.shields.io/badge/Prepare%20-ICPC-%23db164b

![](https://img.shields.io/badge/Learn%20-Competitive%20Programming-%2314c996)
link badge 2 - https://img.shields.io/badge/Learn%20-Competitive%20Programming-%2314c996

![](https://img.shields.io/badge/Practice%20-Competitive%20Programming-%23c724a1)
link badge 3 -https://img.shields.io/badge/Practice%20-Competitive%20Programming-%23c724a1

![](https://img.shields.io/badge/Practice%20-Programming-%2305eb09)
link badge 4 -https://img.shields.io/badge/Practice%20-Programming-%2305eb09

**Comment by pawarashish564** [comment]
ok I'm on it.

**Comment by pawarashish564** [comment]
Please send the badge Markdown

**Comment by devcss122** [comment]
![](https://img.shields.io/badge/Prepare%20-ICPC-%23db164b
![](https://img.shields.io/badge/Learn%20-Competitive%20Programming-%2314c996
![](https://img.shields.io/badge/Practice%20-Competitive%20Programming-%23c724a1
![](https://img.shields.io/badge/Practice%20-Programming-%2305eb09

**Comment by devcss122** [comment]
Just Put closing parenthesis In these lines .
